'use client';

import { useState } from 'react';

const MAX_PITCH_WORDS = 200;

const GUIDELINE_CHECKS = [
  {
    id: 'readGuidelines',
    label: 'I have read the submissions guidelines in full.',
  },
  {
    id: 'ownBehalf',
    label:
      'I am the author and I am submitting this pitch on my own behalf. I am not a communications/PR firm, consultant, or any other third-party entity.',
  },
  {
    id: 'notElsewhere',
    label:
      'I confirm that this pitch is not currently under consideration with another publication, and that I will withdraw it here before submitting it elsewhere, should my circumstances change.',
  },
  {
    id: 'ownVoice',
    label:
      'I confirm that this pitch reflects my own genuine voice, judgement, and expertise, and has not been generated by artificial intelligence.',
  },
  {
    id: 'noJargon',
    label:
      'I confirm that this pitch avoids jargon and unexplained acronyms or initialisms, and is written for a reader without specialist knowledge of the subject.',
  },
  {
    id: 'noClassified',
    label:
      'I confirm that this pitch contains no classified or controlled unclassified information (CUI).',
  },
];

function countWords(text) {
  const trimmed = text.trim();
  return trimmed === '' ? 0 : trimmed.split(/\s+/).length;
}

export default function SubmissionPortalForm() {
  const [fields, setFields] = useState({
    firstName: '',
    lastName: '',
    email: '',
    bio: '',
    pitch: '',
  });
  const [checks, setChecks] = useState(
    Object.fromEntries(GUIDELINE_CHECKS.map((item) => [item.id, false]))
  );
  // 'idle' | 'submitting' | 'success' | 'error'
  const [status, setStatus] = useState('idle');

  const wordCount = countWords(fields.pitch);
  const allChecked = GUIDELINE_CHECKS.every((item) => checks[item.id]);

  function updateField(name) {
    return (event) => setFields((prev) => ({ ...prev, [name]: event.target.value }));
  }

  function toggleCheck(id) {
    return (event) => setChecks((prev) => ({ ...prev, [id]: event.target.checked }));
  }

  async function handleSubmit(event) {
    event.preventDefault();
    setStatus('submitting');
    try {
      const res = await fetch('/api/submit-pitch', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(fields),
      });
      if (!res.ok) throw new Error('Submission failed');
      setStatus('success');
    } catch {
      setStatus('error');
    }
  }

  return (
    <form className="submission-form" onSubmit={handleSubmit}>
      <section className="submission-form__section">
        <h2>Tell us about yourself</h2>

        <div className="submission-form__row">
          <div className="submission-form__field">
            <label htmlFor="firstName">
              First Name <span className="submission-form__required">*</span>
            </label>
            <input
              id="firstName"
              type="text"
              required
              value={fields.firstName}
              onChange={updateField('firstName')}
            />
          </div>
          <div className="submission-form__field">
            <label htmlFor="lastName">
              Last Name <span className="submission-form__required">*</span>
            </label>
            <input
              id="lastName"
              type="text"
              required
              value={fields.lastName}
              onChange={updateField('lastName')}
            />
          </div>
        </div>

        <div className="submission-form__field">
          <label htmlFor="email">
            Email <span className="submission-form__required">*</span>
          </label>
          <input
            id="email"
            type="email"
            required
            value={fields.email}
            onChange={updateField('email')}
          />
          <p className="submission-form__help">
            Please use your professional/work email if you have one &mdash; it helps us
            confirm your identity.
          </p>
        </div>

        <div className="submission-form__field">
          <label htmlFor="bio">
            Professional Biography <span className="submission-form__required">*</span>
          </label>
          <textarea
            id="bio"
            rows={4}
            required
            value={fields.bio}
            onChange={updateField('bio')}
          />
          <p className="submission-form__help">
            In two to three sentences, set out your current role and employer, together
            with the military, government, academic, professional, or other lived
            experience that qualifies you to write on your proposed subject.
          </p>
        </div>
      </section>

      <section className="submission-form__section">
        <h2>Make your pitch</h2>
        <p className="submission-form__intro">A strong pitch answers three questions</p>
        <ol className="submission-form__pitch-questions">
          <li>What is your argument?</li>
          <li>Why does it matter now?</li>
          <li>Why are you the right writer?</li>
        </ol>

        <div className="submission-form__field">
          <label htmlFor="pitch">
            Your Pitch <span className="submission-form__required">*</span>
          </label>
          <textarea
            id="pitch"
            rows={8}
            required
            value={fields.pitch}
            onChange={updateField('pitch')}
          />
          <div className="submission-form__pitch-footer">
            <p className="submission-form__help">
              Set out your main argument and why it matters to our readers now.
            </p>
            <span
              className={`submission-form__counter${
                wordCount > MAX_PITCH_WORDS ? ' is-over' : ''
              }`}
            >
              {wordCount} / {MAX_PITCH_WORDS} words
            </span>
          </div>
        </div>
      </section>

      <section className="submission-form__section">
        <h2>Confirm the guidelines</h2>

        <div className="submission-form__checkboxes">
          {GUIDELINE_CHECKS.map((item) => (
            <label key={item.id} className="submission-form__checkbox">
              <input
                type="checkbox"
                required
                checked={checks[item.id]}
                onChange={toggleCheck(item.id)}
              />
              <span>{item.label}</span>
            </label>
          ))}
        </div>
      </section>

      <div className="submission-form__submit-row">
        <button
          type="submit"
          className="submission-form__submit"
          disabled={!allChecked || status === 'submitting' || status === 'success'}
        >
          {status === 'submitting' ? 'Submitting…' : 'Submit Pitch'}
        </button>
        <p className="submission-form__privacy-note">
          Your details are used only for editorial review of this pitch and won&rsquo;t be
          shared beyond the Fox and Lion editorial team. See our{' '}
          <a href="/privacy-policy" target="_blank" rel="noopener noreferrer">
            Privacy Policy
          </a>
          .
        </p>
        {status === 'success' && (
          <p className="submission-form__status-note is-success">
            Thanks &mdash; we&rsquo;ve received your pitch and will be in touch if it&rsquo;s
            a fit.
          </p>
        )}
        {status === 'error' && (
          <p className="submission-form__status-note is-error">
            Something went wrong submitting your pitch. Please try again, or email it
            directly to{' '}
            <a href="mailto:foxandlion@advancedgrowinglabs.com">
              foxandlion@advancedgrowinglabs.com
            </a>{' '}
            if the problem persists.
          </p>
        )}
      </div>
    </form>
  );
}
